services:
  frontend-client:
    build: ./frontend/client
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  frontend-admin:
    build: ./frontend/admin
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@db/${MYSQL_DATABASE}
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: